name: flutter_bottom_drawer
description: flutter_bottom_drawer provide simple bottom drawer on flutter
version: 0.0.8
homepage: https://github.com/note11g/flutter_bottom_drawer

environment:
  sdk: '>=2.19.2 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
